Revert "Refactor: Use the "getAnalysisUsage" provided by ScopPass to require ScopInfo."
This breaks compilation for me:

lib/Exchange/ScopLibImporter.cpp:104:3: error:
      use of undeclared identifier 'ScopPass'

This reverts commit f2630036cbbb6fe813ef885630e1e771584bf823.